/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type Vote = "absent" | "abstain" | "no" | "yes";

export interface AgendaItems {
  id: number;
  parliament_id: string;
  session_id: string | null;
  title: string;
}

export interface Ballots {
  id: number;
  minutes_url: string | null;
  parliament_id: string | null;
  results_url: string | null;
  session_item_title: string | null;
  start_time: Timestamp | null;
  title: string | null;
}

export interface CommitteeBudgetReports {
  committee_name: string;
  id: string;
  proposal_id: string;
}

export interface CommitteeReports {
  committee_name: string;
  id: string;
  law_changes: string | null;
  opinion: string;
  proposal_id: string;
  proposal_summary: string;
  reasoning: string | null;
}

export interface CommitteeReportSignatures {
  committee_report_id: string;
  mp_id: number;
}

export interface Committees {
  name: string;
}

export interface Interests {
  category: string | null;
  id: Generated<number>;
  interest: string | null;
  mp_id: number | null;
}

export interface MembersOfParliament {
  constituency: string | null;
  email: string | null;
  first_name: string | null;
  full_name: string | null;
  id: number;
  last_name: string | null;
  minister: boolean | null;
  occupation: string | null;
  phone_number: string | null;
  photo: string | null;
  place_of_birth: string | null;
  place_of_residence: string | null;
  year_of_birth: number | null;
}

export interface Ministers {
  cabinet_id: string | null;
  end_date: Timestamp | null;
  ministry: string;
  mp_id: number;
  start_date: Timestamp;
}

export interface MpCommitteeMemberships {
  committee_name: string;
  end_date: Timestamp | null;
  mp_id: number;
  role: string;
  start_date: Timestamp;
}

export interface MpPartyMemberships {
  end_date: Timestamp | null;
  mp_id: number;
  party_id: string;
  start_date: Timestamp;
}

export interface Objections {
  committee_report_id: string | null;
  id: Generated<number>;
  motion: string | null;
  reasoning: string | null;
}

export interface ObjectionSignatures {
  mp_id: number;
  objection_id: Generated<number>;
}

export interface Parties {
  id: string;
  name: string | null;
}

export interface Sessions {
  date: Timestamp;
  id: string;
}

export interface Speeches {
  id: string;
  mp_id: number;
  parliament_id: string;
  response_to: string | null;
  speech: string;
  start_time: Timestamp;
}

export interface Votes {
  ballot_id: number;
  mp_id: number;
  vote: Vote | null;
}

export interface DB {
  agenda_items: AgendaItems;
  ballots: Ballots;
  committee_budget_reports: CommitteeBudgetReports;
  committee_report_signatures: CommitteeReportSignatures;
  committee_reports: CommitteeReports;
  committees: Committees;
  interests: Interests;
  members_of_parliament: MembersOfParliament;
  ministers: Ministers;
  mp_committee_memberships: MpCommitteeMemberships;
  mp_party_memberships: MpPartyMemberships;
  objection_signatures: ObjectionSignatures;
  objections: Objections;
  parties: Parties;
  sessions: Sessions;
  speeches: Speeches;
  votes: Votes;
}
