name: Database generation test
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, ready_for_review]
    branches: [main]

jobs:
  deploy:
    name: Generate database
    runs-on: ubuntu-latest
    permissions:
      deployments: write
      contents: read
    env:
      DATABASE_HOST: localhost
      DATABASE_URL: postgres://postgres:postgres@localhost/postgres
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
    services:
      db:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Check out repository code
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22

      - name: Install dependencies
        run: make install

      - name: Download data dumps
        run: make data

      - name: Initialize database
        run: make nuke

      - name: Preprocess data
        run: make preprocess

      - name: Populate database
        run: make database
